# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    strategy:
      matrix:
        dotnet-version: [ '6.0.x', '7.0.x' ]
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
        source-url: https://nuget.pkg.github.com/purplepiranhaltd/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.NUGET_OPAYOPAYMENTSNET}}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Create Nuget Package
      run: dotnet pack --configuration Release OpayoPaymentsNet/OpayoPaymentsNet.csproj
    - name: Push Nuget Package
      run: dotnet nuget push OpayoPaymentsNet/bin/Release/*.nupkg -k $NUGET_AUTH_TOKEN
